#pragma once
namespace Utilities
{
	union UnOrderedMultiMapUnion
	{
		void* ptrToDelete = nullptr;
		UnOrderedMultiMap<unsigned char, unsigned char>* CPPmultimap1;
		UnOrderedMultiMap<unsigned char, char>* CPPmultimap2;
		UnOrderedMultiMap<unsigned char, short>* CPPmultimap3;
		UnOrderedMultiMap<unsigned char, unsigned short>* CPPmultimap4;
		UnOrderedMultiMap<unsigned char, int>* CPPmultimap5;
		UnOrderedMultiMap<unsigned char, unsigned int>* CPPmultimap6;
		UnOrderedMultiMap<unsigned char, long long>* CPPmultimap7;
		UnOrderedMultiMap<unsigned char, unsigned long long>* CPPmultimap8;
		UnOrderedMultiMap<unsigned char, float>* CPPmultimap9;
		UnOrderedMultiMap<unsigned char, double>* CPPmultimap10;
		UnOrderedMultiMap<unsigned char, wchar_t>* CPPmultimap11;
		UnOrderedMultiMap<unsigned char, bool>* CPPmultimap12;
		UnOrderedMultiMap<unsigned char, std::wstring>* CPPmultimap13;
		UnOrderedMultiMap<unsigned char, __int64>* CPPmultimap14;

		UnOrderedMultiMap<char, unsigned char>* CPPmultimap15;
		UnOrderedMultiMap<char, char>* CPPmultimap16;
		UnOrderedMultiMap<char, short>* CPPmultimap17;
		UnOrderedMultiMap<char, unsigned short>* CPPmultimap18;
		UnOrderedMultiMap<char, int>* CPPmultimap19;
		UnOrderedMultiMap<char, unsigned int>* CPPmultimap20;
		UnOrderedMultiMap<char, long long>* CPPmultimap21;
		UnOrderedMultiMap<char, unsigned long long>* CPPmultimap22;
		UnOrderedMultiMap<char, float>* CPPmultimap23;
		UnOrderedMultiMap<char, double>* CPPmultimap24;
		UnOrderedMultiMap<char, wchar_t>* CPPmultimap25;
		UnOrderedMultiMap<char, bool>* CPPmultimap26;
		UnOrderedMultiMap<char, std::wstring>* CPPmultimap27;
		UnOrderedMultiMap<char, __int64>* CPPmultimap28;

		UnOrderedMultiMap<short, unsigned char>* CPPmultimap29;
		UnOrderedMultiMap<short, char>* CPPmultimap30;
		UnOrderedMultiMap<short, short>* CPPmultimap31;
		UnOrderedMultiMap<short, unsigned short>* CPPmultimap32;
		UnOrderedMultiMap<short, int>* CPPmultimap33;
		UnOrderedMultiMap<short, unsigned int>* CPPmultimap34;
		UnOrderedMultiMap<short, long long>* CPPmultimap35;
		UnOrderedMultiMap<short, unsigned long long>* CPPmultimap36;
		UnOrderedMultiMap<short, float>* CPPmultimap37;
		UnOrderedMultiMap<short, double>* CPPmultimap38;
		UnOrderedMultiMap<short, wchar_t>* CPPmultimap39;
		UnOrderedMultiMap<short, bool>* CPPmultimap40;
		UnOrderedMultiMap<short, std::wstring>* CPPmultimap41;
		UnOrderedMultiMap<short, __int64>* CPPmultimap42;

		UnOrderedMultiMap<unsigned short, unsigned char>* CPPmultimap43;
		UnOrderedMultiMap<unsigned short, char>* CPPmultimap44;
		UnOrderedMultiMap<unsigned short, short>* CPPmultimap45;
		UnOrderedMultiMap<unsigned short, unsigned short>* CPPmultimap46;
		UnOrderedMultiMap<unsigned short, int>* CPPmultimap47;
		UnOrderedMultiMap<unsigned short, unsigned int>* CPPmultimap48;
		UnOrderedMultiMap<unsigned short, long long>* CPPmultimap49;
		UnOrderedMultiMap<unsigned short, unsigned long long>* CPPmultimap50;
		UnOrderedMultiMap<unsigned short, float>* CPPmultimap51;
		UnOrderedMultiMap<unsigned short, double>* CPPmultimap52;
		UnOrderedMultiMap<unsigned short, wchar_t>* CPPmultimap53;
		UnOrderedMultiMap<unsigned short, bool>* CPPmultimap54;
		UnOrderedMultiMap<unsigned short, std::wstring>* CPPmultimap55;
		UnOrderedMultiMap<unsigned short, __int64>* CPPmultimap56;

		UnOrderedMultiMap<int, unsigned char>* CPPmultimap57;
		UnOrderedMultiMap<int, char>* CPPmultimap58;
		UnOrderedMultiMap<int, short>* CPPmultimap59;
		UnOrderedMultiMap<int, unsigned short>* CPPmultimap60;
		UnOrderedMultiMap<int, int>* CPPmultimap61;
		UnOrderedMultiMap<int, unsigned int>* CPPmultimap62;
		UnOrderedMultiMap<int, long long>* CPPmultimap63;
		UnOrderedMultiMap<int, unsigned long long>* CPPmultimap64;
		UnOrderedMultiMap<int, float>* CPPmultimap65;
		UnOrderedMultiMap<int, double>* CPPmultimap66;
		UnOrderedMultiMap<int, wchar_t>* CPPmultimap67;
		UnOrderedMultiMap<int, bool>* CPPmultimap68;
		UnOrderedMultiMap<int, std::wstring>* CPPmultimap69;
		UnOrderedMultiMap<int, __int64>* CPPmultimap70;

		UnOrderedMultiMap<unsigned int, unsigned char>* CPPmultimap71;
		UnOrderedMultiMap<unsigned int, char>* CPPmultimap72;
		UnOrderedMultiMap<unsigned int, short>* CPPmultimap73;
		UnOrderedMultiMap<unsigned int, unsigned short>* CPPmultimap74;
		UnOrderedMultiMap<unsigned int, int>* CPPmultimap75;
		UnOrderedMultiMap<unsigned int, unsigned int>* CPPmultimap76;
		UnOrderedMultiMap<unsigned int, long long>* CPPmultimap77;
		UnOrderedMultiMap<unsigned int, unsigned long long>* CPPmultimap78;
		UnOrderedMultiMap<unsigned int, float>* CPPmultimap79;
		UnOrderedMultiMap<unsigned int, double>* CPPmultimap80;
		UnOrderedMultiMap<unsigned int, wchar_t>* CPPmultimap81;
		UnOrderedMultiMap<unsigned int, bool>* CPPmultimap82;
		UnOrderedMultiMap<unsigned int, std::wstring>* CPPmultimap83;
		UnOrderedMultiMap<unsigned int, __int64>* CPPmultimap84;

		UnOrderedMultiMap<long long, unsigned char>* CPPmultimap85;
		UnOrderedMultiMap<long long, char>* CPPmultimap86;
		UnOrderedMultiMap<long long, short>* CPPmultimap87;
		UnOrderedMultiMap<long long, unsigned short>* CPPmultimap88;
		UnOrderedMultiMap<long long, int>* CPPmultimap89;
		UnOrderedMultiMap<long long, unsigned int>* CPPmultimap90;
		UnOrderedMultiMap<long long, long long>* CPPmultimap91;
		UnOrderedMultiMap<long long, unsigned long long>* CPPmultimap92;
		UnOrderedMultiMap<long long, float>* CPPmultimap93;
		UnOrderedMultiMap<long long, double>* CPPmultimap94;
		UnOrderedMultiMap<long long, wchar_t>* CPPmultimap95;
		UnOrderedMultiMap<long long, bool>* CPPmultimap96;
		UnOrderedMultiMap<long long, std::wstring>* CPPmultimap97;
		UnOrderedMultiMap<long long, __int64>* CPPmultimap98;

		UnOrderedMultiMap<unsigned long long, unsigned char>* CPPmultimap99;
		UnOrderedMultiMap<unsigned long long, char>* CPPmultimap100;
		UnOrderedMultiMap<unsigned long long, short>* CPPmultimap101;
		UnOrderedMultiMap<unsigned long long, unsigned short>* CPPmultimap102;
		UnOrderedMultiMap<unsigned long long, int>* CPPmultimap103;
		UnOrderedMultiMap<unsigned long long, unsigned int>* CPPmultimap104;
		UnOrderedMultiMap<unsigned long long, long long>* CPPmultimap105;
		UnOrderedMultiMap<unsigned long long, unsigned long long>* CPPmultimap106;
		UnOrderedMultiMap<unsigned long long, float>* CPPmultimap107;
		UnOrderedMultiMap<unsigned long long, double>* CPPmultimap108;
		UnOrderedMultiMap<unsigned long long, wchar_t>* CPPmultimap109;
		UnOrderedMultiMap<unsigned long long, bool>* CPPmultimap110;
		UnOrderedMultiMap<unsigned long long, std::wstring>* CPPmultimap111;
		UnOrderedMultiMap<unsigned long long, __int64>* CPPmultimap112;

		UnOrderedMultiMap<float, unsigned char>* CPPmultimap113;
		UnOrderedMultiMap<float, char>* CPPmultimap114;
		UnOrderedMultiMap<float, short>* CPPmultimap115;
		UnOrderedMultiMap<float, unsigned short>* CPPmultimap116;
		UnOrderedMultiMap<float, int>* CPPmultimap117;
		UnOrderedMultiMap<float, unsigned int>* CPPmultimap118;
		UnOrderedMultiMap<float, long long>* CPPmultimap119;
		UnOrderedMultiMap<float, unsigned long long>* CPPmultimap120;
		UnOrderedMultiMap<float, float>* CPPmultimap121;
		UnOrderedMultiMap<float, double>* CPPmultimap122;
		UnOrderedMultiMap<float, wchar_t>* CPPmultimap123;
		UnOrderedMultiMap<float, bool>* CPPmultimap124;
		UnOrderedMultiMap<float, std::wstring>* CPPmultimap125;
		UnOrderedMultiMap<float, __int64>* CPPmultimap126;

		UnOrderedMultiMap<double, unsigned char>* CPPmultimap127;
		UnOrderedMultiMap<double, char>* CPPmultimap128;
		UnOrderedMultiMap<double, short>* CPPmultimap129;
		UnOrderedMultiMap<double, unsigned short>* CPPmultimap130;
		UnOrderedMultiMap<double, int>* CPPmultimap131;
		UnOrderedMultiMap<double, unsigned int>* CPPmultimap132;
		UnOrderedMultiMap<double, long long>* CPPmultimap133;
		UnOrderedMultiMap<double, unsigned long long>* CPPmultimap134;
		UnOrderedMultiMap<double, float>* CPPmultimap135;
		UnOrderedMultiMap<double, double>* CPPmultimap136;
		UnOrderedMultiMap<double, wchar_t>* CPPmultimap137;
		UnOrderedMultiMap<double, bool>* CPPmultimap138;
		UnOrderedMultiMap<double, std::wstring>* CPPmultimap139;
		UnOrderedMultiMap<double, __int64>* CPPmultimap140;

		UnOrderedMultiMap<wchar_t, unsigned char>* CPPmultimap141;
		UnOrderedMultiMap<wchar_t, char>* CPPmultimap142;
		UnOrderedMultiMap<wchar_t, short>* CPPmultimap143;
		UnOrderedMultiMap<wchar_t, unsigned short>* CPPmultimap144;
		UnOrderedMultiMap<wchar_t, int>* CPPmultimap145;
		UnOrderedMultiMap<wchar_t, unsigned int>* CPPmultimap146;
		UnOrderedMultiMap<wchar_t, long long>* CPPmultimap147;
		UnOrderedMultiMap<wchar_t, unsigned long long>* CPPmultimap148;
		UnOrderedMultiMap<wchar_t, float>* CPPmultimap149;
		UnOrderedMultiMap<wchar_t, double>* CPPmultimap150;
		UnOrderedMultiMap<wchar_t, wchar_t>* CPPmultimap151;
		UnOrderedMultiMap<wchar_t, bool>* CPPmultimap152;
		UnOrderedMultiMap<wchar_t, std::wstring>* CPPmultimap153;
		UnOrderedMultiMap<wchar_t, __int64>* CPPmultimap154;

		UnOrderedMultiMap<bool, unsigned char>* CPPmultimap155;
		UnOrderedMultiMap<bool, char>* CPPmultimap156;
		UnOrderedMultiMap<bool, short>* CPPmultimap157;
		UnOrderedMultiMap<bool, unsigned short>* CPPmultimap158;
		UnOrderedMultiMap<bool, int>* CPPmultimap159;
		UnOrderedMultiMap<bool, unsigned int>* CPPmultimap160;
		UnOrderedMultiMap<bool, long long>* CPPmultimap161;
		UnOrderedMultiMap<bool, unsigned long long>* CPPmultimap162;
		UnOrderedMultiMap<bool, float>* CPPmultimap163;
		UnOrderedMultiMap<bool, double>* CPPmultimap164;
		UnOrderedMultiMap<bool, wchar_t>* CPPmultimap165;
		UnOrderedMultiMap<bool, bool>* CPPmultimap166;
		UnOrderedMultiMap<bool, std::wstring>* CPPmultimap167;
		UnOrderedMultiMap<bool, __int64>* CPPmultimap168;

		UnOrderedMultiMap<std::wstring, unsigned char>* CPPmultimap169;
		UnOrderedMultiMap<std::wstring, char>* CPPmultimap170;
		UnOrderedMultiMap<std::wstring, short>* CPPmultimap171;
		UnOrderedMultiMap<std::wstring, unsigned short>* CPPmultimap172;
		UnOrderedMultiMap<std::wstring, int>* CPPmultimap173;
		UnOrderedMultiMap<std::wstring, unsigned int>* CPPmultimap174;
		UnOrderedMultiMap<std::wstring, long long>* CPPmultimap175;
		UnOrderedMultiMap<std::wstring, unsigned long long>* CPPmultimap176;
		UnOrderedMultiMap<std::wstring, float>* CPPmultimap177;
		UnOrderedMultiMap<std::wstring, double>* CPPmultimap178;
		UnOrderedMultiMap<std::wstring, wchar_t>* CPPmultimap179;
		UnOrderedMultiMap<std::wstring, bool>* CPPmultimap180;
		UnOrderedMultiMap<std::wstring, std::wstring>* CPPmultimap181;
		UnOrderedMultiMap<std::wstring, __int64>* CPPmultimap182;

		UnOrderedMultiMap<__int64, unsigned char>* CPPmultimap183;
		UnOrderedMultiMap<__int64, char>* CPPmultimap184;
		UnOrderedMultiMap<__int64, short>* CPPmultimap185;
		UnOrderedMultiMap<__int64, unsigned short>* CPPmultimap186;
		UnOrderedMultiMap<__int64, int>* CPPmultimap187;
		UnOrderedMultiMap<__int64, unsigned int>* CPPmultimap188;
		UnOrderedMultiMap<__int64, long long>* CPPmultimap189;
		UnOrderedMultiMap<__int64, unsigned long long>* CPPmultimap190;
		UnOrderedMultiMap<__int64, float>* CPPmultimap191;
		UnOrderedMultiMap<__int64, double>* CPPmultimap192;
		UnOrderedMultiMap<__int64, wchar_t>* CPPmultimap193;
		UnOrderedMultiMap<__int64, bool>* CPPmultimap194;
		UnOrderedMultiMap<__int64, std::wstring>* CPPmultimap195;
		UnOrderedMultiMap<__int64, __int64>* CPPmultimap196;
	};
}